set_property PACKAGE_PIN R14 [get_ports {Dout[0]}]
set_property PACKAGE_PIN P14 [get_ports {Dout[1]}]
set_property PACKAGE_PIN N16 [get_ports {Dout[2]}]
set_property PACKAGE_PIN M14 [get_ports {Dout[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {Dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Dout[0]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
